name: "Test"
on: 
  push:
    branches: [ llvm ]
  pull_request:
    branches: [ llvm ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Build
        working-directory: front
        run: |
          cmake ./
          make

      - name: Unit tests
        working-directory: front
        run: build/test